2020:04:01 13:02:44:144873 ~ Traceback (most recent call last):
  File "C:\SDK\Anaconda3\lib\site-packages\pydebugger\debug.py", line 222, in read_config
    data = self.cfg.get(section, option)
  File "C:\SDK\Anaconda3\lib\configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\SDK\Anaconda3\lib\configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'DEBUG'

2020:04:01 13:02:45:234010 ~ Traceback (most recent call last):
  File "D:\TOOLS\pyx\gitdate.py", line 218, in notify
    import PySnarl
ModuleNotFoundError: No module named 'PySnarl'

2020:04:01 13:02:46:367343 ~ Traceback (most recent call last):
  File "D:\TOOLS\pyx\gitdate.py", line 218, in notify
    import PySnarl
ModuleNotFoundError: No module named 'PySnarl'

2020:04:01 13:02:47:659350 ~ Traceback (most recent call last):
  File "D:\TOOLS\pyx\gitdate.py", line 218, in notify
    import PySnarl
ModuleNotFoundError: No module named 'PySnarl'

2020:04:01 13:02:48:685246 ~ Traceback (most recent call last):
  File "D:\TOOLS\pyx\gitdate.py", line 218, in notify
    import PySnarl
ModuleNotFoundError: No module named 'PySnarl'

2020:04:01 13:02:49:515794 ~ Traceback (most recent call last):
  File "D:\TOOLS\pyx\gitdate.py", line 732, in commit
    if 'https:' in host or 'http:' in host or 'ssh:' in host or 'git:' in host:
TypeError: argument of type 'bool' is not iterable

